### ISSUE TITLE
Not enough libraries in the #include part

### ISSUE THREAD

**Issue by Yerima18** [metflekx/CHEM#1]
The code uses std::setprecision(9) to set the precision of the output when printing the molar mass. Ensure that you have included the #iomanip(library) header for using std::setprecision

**Comment by ma-habibi** [comment]
thank you @Yerima18, that's right the main is relying iomanip being indirectly included by iostream, which is bad practice.
but this main.cpp file is to be deleted in the next commit, as this project is focused on CHEM file.
