### ISSUE TITLE
add a new column ValenceElectrons  to `data.csv`

### ISSUE THREAD

**Issue by ma-habibi** [metflekx/CHEM#19]
please add a column _ValenceElectrons_ to `data.csv`.
so that the column stores  the number of valence electrons each element have.

* you can calculate the number of valence electrons using the _GroupBlock_ column which already is in `data.csv` :
<img width="289" alt="Screenshot 2023-08-26 at 22 36 04" src="https://github.com/metflekx/CHEM/assets/106245122/77566610-9e68-4e6d-9c0f-13c56c2de2f0">

**Comment by ankits57** [comment]
Hello, i have added valenece Electron column in data.csv
