### ISSUE TITLE
web scraping to add data about elements

### ISSUE THREAD

**Issue by ma-habibi** [metflekx/CHEM#4]
> scrape this wikipedia page : 
    https://en.wikipedia.org/wiki/Densities_of_the_elements_(data_page)

to add a density column to 'data.csv'. (in g/cm^3)

**Comment by IshitarTyagi** [comment]
[data.csv](https://github.com/metflekx/CHEM/files/12366242/data.csv)
CSV file contains element data with element name, symbol, and density. Extracted from HTML table. Helpful for data analysis.
